"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-26 16:05:51.324971
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "games",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("mode", sa.String(length=20), nullable=False),
        sa.Column("settings", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("winner_position", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("games", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_games_status"), ["status"], unique=False)

    op.create_table(
        "players",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.Column("color", sa.String(length=7), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("archived_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "game_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("segment", sa.Integer(), nullable=True),
        sa.Column("multiplier", sa.Integer(), nullable=True),
        sa.Column("x_mm", sa.Double(), nullable=True),
        sa.Column("y_mm", sa.Double(), nullable=True),
        sa.Column("source", sa.String(length=10), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["game_id"], ["games.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("game_id", "seq"),
    )
    with op.batch_alter_table("game_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_game_events_game_id"), ["game_id"], unique=False)

    op.create_table(
        "game_players",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=True),
        sa.Column("guest_name", sa.String(length=40), nullable=True),
        sa.Column("stats", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["game_id"], ["games.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("game_id", "position"),
    )
    with op.batch_alter_table("game_players", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_game_players_game_id"), ["game_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_game_players_player_id"), ["player_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("game_players", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_game_players_player_id"))
        batch_op.drop_index(batch_op.f("ix_game_players_game_id"))

    op.drop_table("game_players")
    with op.batch_alter_table("game_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_game_events_game_id"))

    op.drop_table("game_events")
    op.drop_table("players")
    with op.batch_alter_table("games", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_games_status"))

    op.drop_table("games")
    # ### end Alembic commands ###
