"""detection confidence

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-26 17:39:01.292030
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("game_events", schema=None) as batch_op:
        batch_op.add_column(sa.Column("confidence", sa.Double(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("game_events", schema=None) as batch_op:
        batch_op.drop_column("confidence")

    # ### end Alembic commands ###
