"""player preferences

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-26 17:41:49.983476
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("players", schema=None) as batch_op:
        batch_op.add_column(sa.Column("favorite_double", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("throwing_hand", sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column("default_mode", sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("players", schema=None) as batch_op:
        batch_op.drop_column("default_mode")
        batch_op.drop_column("throwing_hand")
        batch_op.drop_column("favorite_double")

    # ### end Alembic commands ###
